"""Add pre-computed responses for all models missing coverage."""
import asyncio
import aiosqlite
from config import DATABASE_PATH

# Responses for models that need them, keyed by prompt_id -> model_id -> content
# Only adding for models/prompts that don't already exist
NEW_RESPONSES = {
    1: {  # Giải thích blockchain cho học sinh lớp 10
        "claude-sonnet": "Blockchain là công nghệ lưu trữ dữ liệu theo chuỗi khối, mỗi khối nối với khối trước bằng mã hóa.\n\nHãy tưởng tượng lớp bạn có một cuốn sổ chung. Mỗi khi ai ghi thêm một dòng, tất cả bạn trong lớp đều kiểm tra và xác nhận. Không ai có thể lén sửa vì mọi người đều giữ bản sao.\n\n**3 điểm cần nhớ:**\n- Phi tập trung: không có \"thầy giáo\" kiểm soát sổ\n- Minh bạch: ai cũng xem được\n- An toàn: sửa 1 chỗ thì phải sửa toàn bộ chuỗi — gần như không thể\n\nỨng dụng phổ biến: tiền điện tử (Bitcoin), hợp đồng thông minh, theo dõi hàng hóa.",
        "gemini-flash": "Blockchain = chuỗi khối dữ liệu được mã hóa và liên kết với nhau.\n\nCách dễ hiểu nhất: nghĩ về một file Google Sheets mà cả trường cùng xem. Mỗi dòng mới được thêm vào cuối, không ai xóa được dòng cũ, và mọi thay đổi đều hiện rõ cho tất cả.\n\nĐiểm khác biệt lớn: không có Google (công ty trung gian) kiểm soát — tất cả máy tính trong mạng cùng giữ bản sao và xác nhận lẫn nhau.\n\nỨng dụng: Bitcoin, NFT, chuỗi cung ứng, bỏ phiếu điện tử.",
        "grok-4": "Blockchain? Đơn giản thôi.\n\nTưởng tượng bạn và 1000 người cùng chơi một game online. Mỗi hành động của bất kỳ ai đều được ghi lại, mọi người đều thấy, và KHÔNG CÓ ADMIN nào có thể gian lận.\n\nĐó là blockchain — một hệ thống ghi chép mà:\n1. Ai cũng thấy (minh bạch)\n2. Không ai xóa được (bất biến)\n3. Không cần tin ai cả — toán học bảo đảm (phi tập trung)\n\nBitcoin dùng blockchain để chuyển tiền không cần ngân hàng. Ethereum mở rộng thêm \"hợp đồng thông minh\" — tự động thực thi khi đủ điều kiện.",
        "llama-4": "Blockchain là một sổ cái kỹ thuật số phân tán.\n\nCách hoạt động:\n1. Dữ liệu được nhóm thành các \"khối\" (block)\n2. Mỗi khối chứa mã hash của khối trước → tạo \"chuỗi\" (chain)\n3. Hàng nghìn máy tính giữ bản sao giống nhau\n4. Muốn thêm khối mới → phải được đa số đồng ý (cơ chế đồng thuận)\n\nKết quả: dữ liệu minh bạch, chống giả mạo, không cần bên thứ ba.\n\n**Ví dụ thực tế:**\n- Bitcoin: chuyển tiền ngang hàng\n- Supply chain: truy xuất nguồn gốc café từ nông trại đến quán\n- Gaming: sở hữu vật phẩm thực sự (NFT)",
        "qwen-35": "Blockchain 区块链 — dịch ra là \"chuỗi khối\".\n\nEm hãy hình dung: một cuốn sổ kế toán mà không ai sở hữu riêng, nhưng ai cũng có bản sao. Mỗi trang mới (block) ghi lại giao dịch và được \"niêm phong\" bằng mật mã, nối với trang trước.\n\nĐặc điểm:\n- **Phân tán:** không server trung tâm, hàng nghìn node giữ dữ liệu\n- **Bất biến:** đã ghi thì không sửa được\n- **Đồng thuận:** thêm dữ liệu mới cần >50% mạng lưới đồng ý\n\nBitcoin là ứng dụng đầu tiên của blockchain (2009). Hiện tại blockchain còn dùng cho DeFi, NFT, quản lý chuỗi cung ứng.",
        "glm-5": "Blockchain (chuỗi khối) là công nghệ lưu trữ dữ liệu phi tập trung.\n\nHiểu đơn giản: thay vì một ngân hàng giữ sổ sách, hàng triệu máy tính cùng giữ bản sao giống nhau. Mỗi \"khối\" dữ liệu được mã hóa và nối với khối trước, tạo thành chuỗi không thể phá vỡ.\n\nƯu điểm: minh bạch, an toàn, không cần trung gian.\nNhược điểm: tốn năng lượng, xử lý chậm hơn hệ thống tập trung.\n\nỨng dụng nổi bật: Bitcoin, Ethereum, quản lý chuỗi cung ứng, y tế số.",
        "kimi-k25": "Blockchain = sổ cái + mã hóa + phi tập trung.\n\n**Ví dụ dễ hiểu:** Lớp bạn có 40 học sinh. Mỗi khi ai mượn/trả tiền, tất cả 40 người đều ghi vào sổ của mình. Muốn gian lận? Phải sửa cùng lúc hơn 20 cuốn sổ — bất khả thi!\n\nĐó chính là cách blockchain hoạt động:\n- Giao dịch → đóng gói thành khối\n- Khối → được mã hóa, nối vào chuỗi\n- Chuỗi → được sao chép ra hàng nghìn máy\n\nKết quả: không ai gian lận được, không cần ngân hàng. Bitcoin, Ethereum đều dùng công nghệ này.",
        "mistral-l2": "Blockchain est... à, xin lỗi, để giải thích bằng tiếng Việt nhé!\n\nBlockchain là hệ thống cơ sở dữ liệu phân tán, nơi thông tin được lưu trong các \"khối\" liên kết bằng mật mã.\n\n**Nguyên lý cốt lõi:**\n1. **Phân tán (Decentralized):** Không có server trung tâm — mỗi node giữ toàn bộ bản sao\n2. **Bất biến (Immutable):** Hash của khối trước được nhúng vào khối sau — sửa 1 khối = phá vỡ toàn chuỗi\n3. **Đồng thuận (Consensus):** Proof-of-Work hoặc Proof-of-Stake xác minh giao dịch\n\nỨng dụng: cryptocurrency, smart contracts, DeFi, supply chain tracking.",
    },
    2: {  # Viết bài thơ lục bát về mùa xuân Hà Nội
        "claude-sonnet": "Xuân về nắng nhẹ Hồ Tây,\nCánh đào e ấp, hương bay dịu dàng.\nPhố phường lặng lẽ sương vàng,\nBước chân ai đó lang thang chiều nào.\n\nMùi trầm vương vấn đêm giao,\nPháo hoa rực rỡ, xôn xao lòng người.\nHà thành bốn mùa chẳng phai,\nNhưng xuân riêng một góc trời thương nhau.",
        "gemini-flash": "Hà Nội xuân đến dịu êm,\nHồ Gươm sóng lặng, trăng đêm lung linh.\nPhố cổ rêu phong hữu tình,\nHoa đào khoe sắc bên mình nắng mai.\n\nGió xuân nhẹ thoảng vai ai,\nHương cốm vương vấn, miệt mài nhớ thương.\nMùa xuân Hà Nội phố phường,\nĐẹp như bức họa, vấn vương lòng người.",
        "grok-4": "Xuân sang phố cổ Hà thành,\nĐào phai lấm tấm, long lanh sương mai.\nTrà nóng quán cóc vỉa hè dài,\nÔng đồ phố Bưởi bày khai bút thần.\n\nMưa phùn giăng mắc bước chân,\nHương trầm quyện gió, tần ngần nhớ ai.\nXuân đi xuân đến miệt mài,\nHà Nội vẫn đẹp, chẳng phai bao giờ.",
        "deepseek": "Hà Nội mùa xuân dịu dàng,\nĐào tơ nở rộ khắp hàng phố quen.\nHồ Gươm gió nhẹ êm đềm,\nTháp Rùa in bóng bên thềm cỏ xanh.\n\nChợ hoa rực rỡ sắc màu,\nMùi hương thoang thoảng bên cầu Thê Húc.\nXuân về ấm áp trong lòng,\nHà thành nghìn tuổi, mênh mông tình người.",
        "llama-4": "Xuân sang phố nhỏ Hà Nội,\nMưa bay lất phất, bầu trời xám tro.\nĐào hồng chen lẫn mai vàng,\nPhố phường nhộn nhịp, rộn ràng Tết sang.\n\nBà cụ bán hoa vỉa hè,\nNụ cười hiền hậu, chẳng hề lo toan.\nXuân Hà Nội, nét dịu dàng,\nNhư ly trà nóng, nhẹ nhàng ấm tim.",
        "qwen-35": "Hà thành xuân đến êm êm,\nHồ Tây lặng sóng, trời đêm dịu hiền.\nĐường hoa Nhật Tản ven miền,\nĐào phai khoe sắc, ưu phiền tan đi.\n\nPhố xưa gánh hàng nối nhau,\nBánh chưng xanh lá, trầu cau đỏ tình.\nXuân ơi xuân đẹp lung linh,\nHà Nội trong mắt chúng mình đẹp sao.",
        "glm-5": "Xuân Hà Nội nhẹ như mơ,\nĐào tơ nở thắm bên bờ hồ xanh.\nPhố cổ rêu phong thành thành,\nGánh hoa rực rỡ, nắng vàng dịu êm.\n\nChuông chùa ngân vọng đêm đêm,\nHương trầm thanh tịnh, lòng thêm bình yên.\nXuân sang mang lại niềm tin,\nHà thành vạn thuở, ân tình không phai.",
        "kimi-k25": "Hà Nội xuân sang sớm mai,\nSương giăng phố cổ, heo may nhẹ nhàng.\nĐào phai e thẹn bên đường,\nHoa mai vàng rực, phố phường đón xuân.\n\nCốm xanh gói lá bình dân,\nTrà sen Tây Hồ, thanh tân lạ kỳ.\nXuân đi rồi xuân lại về,\nHà thành muôn thuở, tình quê mặn nồng.",
        "mistral-l2": "Xuân về Hà Nội hân hoan,\nHoa đào rực rỡ, muôn ngàn sắc hương.\nHồ Gươm sáng sớm tinh sương,\nNgười đi thể dục, con đường thênh thang.\n\nPhố phường rộn rã tiếng vang,\nMùa xuân gõ cửa, huy hoàng nắng lên.\nHà thành duyên dáng êm đềm,\nMùa xuân ký ức, bên thềm nhớ thương.",
    },
    3: {  # Tại sao kinh tế Việt Nam tăng trưởng nhanh
        "claude-sonnet": "Kinh tế Việt Nam tăng trưởng nhanh nhờ 4 yếu tố:\n\n**1. Hưởng lợi từ chiến lược China+1:** Các tập đoàn lớn như Samsung, Apple, Intel dịch chuyển sản xuất từ Trung Quốc sang VN. VN trở thành hub sản xuất điện tử hàng đầu ASEAN.\n\n**2. Mạng lưới FTA rộng:** 16 hiệp định thương mại tự do (CPTPP, EVFTA, RCEP) giúp hàng VN vào thị trường EU, Mỹ, Nhật với thuế ưu đãi.\n\n**3. Dân số trẻ, chi phí thấp:** 70% dân số dưới 35, năng suất tốt, lương cạnh tranh. Thị trường nội địa 100 triệu người tiêu dùng.\n\n**4. Chuyển đổi số nhanh:** Fintech, e-commerce bùng nổ. Thanh toán không tiền mặt tăng 40%/năm.\n\n**Thách thức:** phụ thuộc FDI, hạ tầng cần cải thiện, thiếu nhân lực chất lượng cao.",
        "gemini-flash": "3 từ: Vị trí — Con người — Thời điểm.\n\n**Vị trí:** Nằm giữa chuỗi cung ứng châu Á, cảng biển thuận lợi, giáp Trung Quốc.\n\n**Con người:** Dân số trẻ (trung vị 31 tuổi), ham học hỏi, chi phí lao động chỉ bằng 1/3 Trung Quốc.\n\n**Thời điểm:** Chiến tranh thương mại Mỹ-Trung → doanh nghiệp cần alternative → VN sẵn sàng đón nhận.\n\nThêm vào đó: 16 FTA mở cửa thị trường xuất khẩu, chính phủ ổn định, lạm phát kiểm soát tốt.\n\nRủi ro: bẫy thu nhập trung bình, thiếu R&D nội địa, phụ thuộc Samsung (chiếm 20% xuất khẩu).",
        "grok-4": "Tại sao VN tăng trưởng nhanh? Vì đúng người, đúng thời điểm, đúng chiến lược.\n\n**Đúng thời điểm:** Mỹ-Trung đánh nhau, VN hưởng lợi. Hàng trăm nhà máy rời Trung Quốc sang VN.\n\n**Đúng người:** 100 triệu dân, 70% dưới 35. Trẻ, tech-savvy, chịu khó. TikTok Shop VN top 2 thế giới — nói lên tất cả.\n\n**Đúng chiến lược:** Ký FTA khắp nơi, mở cửa cho FDI, giữ vĩ mô ổn định.\n\nCâu hỏi thật sự không phải \"tại sao tăng nhanh\" mà là \"có giữ được không?\" — đó mới là bài toán khó.",
        "llama-4": "Kinh tế VN tăng trưởng vượt kỳ vọng nhờ:\n\n1. **FDI dồi dào:** Chiến lược China+1 đưa Samsung, Intel, Apple vào VN. Vốn FDI đăng ký liên tục đạt kỷ lục.\n\n2. **Thương mại mở:** Tổng kim ngạch XNK gấp 2 lần GDP — thuộc top thế giới. 16 FTA tạo lợi thế thuế quan.\n\n3. **Nhân khẩu học thuận lợi:** Dân số vàng, đô thị hóa nhanh, tầng lớp trung lưu mở rộng → tiêu dùng nội địa tăng mạnh.\n\n4. **Kinh tế số:** E-commerce tăng 25%/năm, fintech phát triển nhanh nhất ASEAN.\n\nRủi ro cần lưu ý: phụ thuộc xuất khẩu, biến đổi khí hậu, năng suất lao động còn thấp so với khu vực.",
        "qwen-35": "Việt Nam đang ở \"điểm ngọt\" của phát triển kinh tế. Có 5 động lực chính:\n\n1. **Chiến lược China+1:** Doanh nghiệp đa quốc gia đa dạng hóa chuỗi cung ứng khỏi TQ → VN là lựa chọn số 1\n2. **FTA toàn diện:** CPTPP + EVFTA + RCEP mở rộng thị trường xuất khẩu\n3. **Dân số vàng:** 100 triệu dân, trung vị 31 tuổi, lực lượng lao động dồi dào\n4. **Ổn định vĩ mô:** Lạm phát <4%, tỷ giá kiểm soát, nợ công trong tầm quản lý\n5. **Số hóa nhanh:** 78% dân dùng smartphone, e-commerce và fintech bùng nổ\n\nThách thức lớn nhất: thoát bẫy thu nhập trung bình, nâng cao năng suất, và giảm phụ thuộc FDI.",
        "glm-5": "Kinh tế VN tăng trưởng nhanh nhờ 3 trụ cột:\n\n**Trụ cột 1 — Xuất khẩu:** VN là công xưởng mới của thế giới. Samsung sản xuất 50% điện thoại tại VN. Kim ngạch xuất khẩu tăng đều 10-15%/năm.\n\n**Trụ cột 2 — FDI:** Vốn đầu tư nước ngoài đổ vào liên tục. Nhà máy mới mọc lên ở Bắc Ninh, Hải Phòng, Bình Dương.\n\n**Trụ cột 3 — Tiêu dùng nội địa:** 100 triệu dân, tầng lớp trung lưu tăng nhanh, mua sắm online bùng nổ.\n\nĐiểm yếu: phụ thuộc FDI, thiếu công nghệ lõi, hạ tầng logistics chưa đồng bộ.",
        "kimi-k25": "VN tăng trưởng nhanh vì đang hưởng lợi từ một \"cơn bão hoàn hảo\" của các yếu tố thuận lợi:\n\n- **Địa chính trị:** Mỹ-Trung căng thẳng → doanh nghiệp cần alternative → VN sẵn sàng\n- **Nhân lực:** Trẻ, đông, chi phí thấp. Kỹ sư IT VN ngày càng được đánh giá cao\n- **Thương mại:** 16 FTA — nhiều nhất ASEAN. Xuất khẩu dễ dàng sang EU, Mỹ, Nhật\n- **Số hóa:** Thanh toán điện tử, e-commerce, ride-hailing phát triển cực nhanh\n\nNhưng cần cảnh giác: nếu không đầu tư R&D và giáo dục, VN sẽ mắc kẹt ở khâu gia công mãi.",
        "mistral-l2": "L'économie vietnamienne... À, xin lỗi — tiếng Việt nhé!\n\nVN tăng trưởng nhanh nhờ:\n\n1. **Chiến lược đa dạng hóa chuỗi cung ứng (China+1):** Doanh nghiệp toàn cầu giảm phụ thuộc TQ, VN là điểm đến hàng đầu\n2. **Hiệp định thương mại tự do:** 16 FTA mở cánh cửa xuất khẩu sang hầu hết thị trường lớn\n3. **Chi phí cạnh tranh:** Lương trung bình ~$300/tháng, thấp hơn TQ, Thái Lan\n4. **Ổn định chính trị:** Một trong ít nước ASEAN duy trì ổn định liên tục\n\nLe défi principal: chuyển từ gia công sang sáng tạo — đó là bài toán của thập kỷ tới.",
    },
    4: {  # Viết hàm Python sắp xếp tên tiếng Việt
        "claude-sonnet": "```python\nfrom functools import cmp_to_key\nimport unicodedata\n\n# Bảng chữ cái tiếng Việt (không dấu thanh)\nVN_BASE = 'aăâbcdđeêghiklmnoôơpqrstuưvxy'\n\ndef normalize_char(c):\n    \"\"\"Tách ký tự thành (chữ cái gốc, thứ tự dấu thanh)\"\"\"\n    decomposed = unicodedata.normalize('NFD', c.lower())\n    base = decomposed[0]\n    # Xử lý đ riêng\n    if c.lower() == 'đ':\n        return ('đ', 0)\n    tone = 0\n    for ch in decomposed[1:]:\n        if unicodedata.category(ch) == 'Mn':\n            tone = ord(ch)\n    return (base, tone)\n\ndef vn_compare(a, b):\n    for ca, cb in zip(a.lower(), b.lower()):\n        na, ta = normalize_char(ca)\n        nb, tb = normalize_char(cb)\n        ia = VN_BASE.find(na) if na in VN_BASE else ord(na) + 100\n        ib = VN_BASE.find(nb) if nb in VN_BASE else ord(nb) + 100\n        if ia != ib: return ia - ib\n        if ta != tb: return ta - tb\n    return len(a) - len(b)\n\ndef sort_vietnamese_names(names: list[str]) -> list[str]:\n    return sorted(names, key=cmp_to_key(vn_compare))\n\n# Test\nnames = ['Nguyễn Văn An', 'Trần Thị Bình', 'Đỗ Minh Châu', 'Lê Hoàng Ân', 'Phạm Đức Anh']\nprint(sort_vietnamese_names(names))\n```",
        "gemini-flash": "```python\nimport unicodedata\n\nVIET_ALPHABET = 'aăâbcdđeêghiklmnoôơpqrstuưvxy'\nTONES = ['', '\\u0300', '\\u0301', '\\u0303', '\\u0309', '\\u0323']  # ngang, huyền, sắc, ngã, hỏi, nặng\n\ndef sort_key(name: str) -> list[tuple[int, int]]:\n    result = []\n    for char in unicodedata.normalize('NFD', name.lower()):\n        if char in VIET_ALPHABET:\n            result.append((VIET_ALPHABET.index(char), 0))\n        elif unicodedata.category(char) == 'Mn':  # dấu thanh\n            idx = TONES.index(char) if char in TONES else 6\n            if result:\n                result[-1] = (result[-1][0], idx)\n        elif char == ' ':\n            result.append((-1, 0))  # khoảng trắng đứng trước\n    return result\n\nnames = ['Nguyễn Văn An', 'Đỗ Châu', 'Trần Bình', 'Lê Ân', 'Phạm Anh']\nprint(sorted(names, key=sort_key))\n```",
        "grok-4": "```python\n# Cách nhanh nhất: dùng thư viện locale\nimport locale\nlocale.setlocale(locale.LC_ALL, 'vi_VN.UTF-8')\n\ndef sort_viet(names: list[str]) -> list[str]:\n    return sorted(names, key=locale.strxfrm)\n\n# Nếu locale không available, dùng manual mapping:\nORDER = {c: i for i, c in enumerate('aàáảãạăằắẳẵặâầấẩẫậbcdđeèéẻẽẹêềếểễệghiìíỉĩịklmnoòóỏõọôồốổỗộơờớởỡợpqrstuùúủũụưừứửữựvxyỳýỷỹỵ')}\n\ndef sort_viet_manual(names: list[str]) -> list[str]:\n    def key(name):\n        return [ORDER.get(c, ord(c) + 1000) for c in name.lower()]\n    return sorted(names, key=key)\n\nnames = ['Nguyễn Văn An', 'Đỗ Châu', 'Trần Bình', 'Lê Ân']\nprint(sort_viet(names))\nprint(sort_viet_manual(names))\n```",
        "deepseek": "```python\nimport unicodedata\n\nALPHA = list('aăâbcdđeêghiklmnoôơpqrstuưvxy')\nTONE_MARKS = {'\\u0300': 1, '\\u0301': 2, '\\u0303': 3, '\\u0309': 4, '\\u0323': 5}\n\ndef vn_key(text: str):\n    keys = []\n    for ch in unicodedata.normalize('NFD', text.lower()):\n        if ch in ALPHA:\n            keys.append((ALPHA.index(ch), 0))\n        elif ch in TONE_MARKS:\n            if keys:\n                keys[-1] = (keys[-1][0], TONE_MARKS[ch])\n        elif ch.isalpha():\n            keys.append((ord(ch) + 100, 0))\n    return keys\n\ndef sort_vn(names):\n    return sorted(names, key=vn_key)\n\nprint(sort_vn(['Nguyễn An', 'Đỗ Châu', 'Trần Bình', 'Lê Ân']))\n```",
        "llama-4": "```python\nfrom functools import cmp_to_key\n\n# Full Vietnamese character order\nVN_CHARS = (\n    'aàáảãạ' 'ăằắẳẵặ' 'âầấẩẫậ' 'b' 'c' 'd' 'đ'\n    'eèéẻẽẹ' 'êềếểễệ' 'g' 'h' 'iìíỉĩị' 'k' 'l' 'm' 'n'\n    'oòóỏõọ' 'ôồốổỗộ' 'ơờớởỡợ' 'p' 'q' 'r' 's' 't'\n    'uùúủũụ' 'ưừứửữự' 'v' 'x' 'yỳýỷỹỵ'\n)\nORDER = {c: i for i, c in enumerate(VN_CHARS)}\n\ndef compare(a: str, b: str) -> int:\n    a, b = a.lower(), b.lower()\n    for x, y in zip(a, b):\n        ox = ORDER.get(x, ord(x) + 500)\n        oy = ORDER.get(y, ord(y) + 500)\n        if ox != oy:\n            return -1 if ox < oy else 1\n    return len(a) - len(b)\n\nnames = ['Nguyễn An', 'Đỗ Châu', 'Trần Bình', 'Lê Ân']\nprint(sorted(names, key=cmp_to_key(compare)))\n```",
        "qwen-35": "```python\nimport unicodedata\nfrom typing import List\n\nclass VietnameseSorter:\n    ALPHABET = 'aăâbcdđeêghiklmnoôơpqrstuưvxy'\n    TONE_ORDER = {0: 0, 0x300: 1, 0x309: 2, 0x303: 3, 0x301: 4, 0x323: 5}\n\n    @classmethod\n    def _char_key(cls, char: str) -> tuple:\n        decomposed = unicodedata.normalize('NFD', char.lower())\n        base = decomposed[0] if decomposed[0] != '\\u0111' else 'đ'\n        tone = 0\n        for c in decomposed:\n            if unicodedata.category(c) == 'Mn':\n                tone = ord(c)\n        alpha_idx = cls.ALPHABET.find(base)\n        if alpha_idx == -1:\n            alpha_idx = ord(base) + 100\n        return (alpha_idx, cls.TONE_ORDER.get(tone, 6))\n\n    @classmethod\n    def sort(cls, names: List[str]) -> List[str]:\n        return sorted(names, key=lambda n: [cls._char_key(c) for c in n])\n\nprint(VietnameseSorter.sort(['Nguyễn An', 'Đỗ Châu', 'Trần Bình']))\n```",
        "glm-5": "```python\nimport re\nimport unicodedata\n\ndef vietnamese_sort_key(name: str) -> str:\n    \"\"\"Tạo sort key cho tên tiếng Việt.\"\"\"\n    CHAR_MAP = 'aăâbcdđeêghiklmnoôơpqrstuưvxy'\n    decomposed = unicodedata.normalize('NFD', name.lower())\n    key = []\n    for ch in decomposed:\n        if ch in CHAR_MAP:\n            key.append(chr(ord('A') + CHAR_MAP.index(ch)))\n        elif unicodedata.category(ch) == 'Mn':\n            key.append(ch)  # giữ dấu thanh để phân biệt\n        elif ch == ' ':\n            key.append(' ')\n    return ''.join(key)\n\nnames = ['Nguyễn An', 'Đỗ Châu', 'Trần Bình', 'Lê Ân']\nprint(sorted(names, key=vietnamese_sort_key))\n```",
        "kimi-k25": "```python\n# Cách đơn giản nhất dùng unidecode + custom mapping\nfrom unidecode import unidecode\n\ndef vn_sort_key(name: str) -> tuple:\n    # Tách họ, tên đệm, tên\n    parts = name.strip().split()\n    if len(parts) >= 2:\n        # Sắp xếp theo tên (cuối) trước, rồi họ\n        return (unidecode(parts[-1]).lower(), unidecode(parts[0]).lower())\n    return (unidecode(name).lower(),)\n\nnames = ['Nguyễn Văn An', 'Đỗ Minh Châu', 'Trần Bình', 'Lê Ân']\nprint(sorted(names, key=vn_sort_key))\n# Kết quả sắp xếp theo tên: An, Ân, Bình, Châu\n```\n\n**Lưu ý:** Cách này sắp xếp theo tên (phong cách VN). Nếu muốn sắp theo họ, đổi thứ tự trong tuple.",
        "mistral-l2": "```python\nimport unicodedata\nfrom typing import List, Tuple\n\n# Vietnamese alphabet order\nVN_ORDER: str = 'aăâbcdđeêghiklmnoôơpqrstuưvxy'\n\ndef decompose(char: str) -> Tuple[int, int]:\n    nfd = unicodedata.normalize('NFD', char.lower())\n    base = nfd[0]\n    tone = sum(ord(c) for c in nfd if unicodedata.category(c) == 'Mn')\n    base_idx = VN_ORDER.find(base)\n    return (base_idx if base_idx >= 0 else ord(base) + 200, tone)\n\ndef sort_vietnamese(names: List[str]) -> List[str]:\n    return sorted(names, key=lambda n: [decompose(c) for c in n])\n\n# Example\nnames = ['Nguyễn An', 'Đỗ Châu', 'Trần Bình', 'Lê Ân']\nfor name in sort_vietnamese(names):\n    print(name)\n```",
    },
    5: {  # So sánh phở Hà Nội và phở Sài Gòn
        "claude-sonnet": "Phở Hà Nội và phở Sài Gòn là hai trường phái ẩm thực đại diện cho hai tính cách vùng miền.\n\n**Phở Hà Nội:** Thanh đạm, tinh tế. Nước dùng trong, ngọt xương. Bánh phở mỏng. Ăn kèm đơn giản: hành lá, mùi, quẩy. Không có rau sống, không tương đen.\n\n**Phở Sài Gòn:** Phóng khoáng, đầy đặn. Nước ngọt đậm, có vị hồi. Bánh phở to bản. \"Vườn rau\" trên bàn: giá, húng quế, ngò gai, chanh, ớt. Tương đen + tương ớt tự do.\n\n**Điểm chung:** Cả hai đều là niềm tự hào ẩm thực Việt. Gốc phở từ Nam Định, nhưng đã phát triển thành hai phiên bản riêng biệt.\n\nKhông có phở nào \"đúng\" hơn — chỉ là bạn thích tối giản hay phong phú.",
        "gemini-flash": "**Phở Bắc vs Phở Nam — Cuộc chiến không hồi kết!**\n\n| Tiêu chí | Hà Nội | Sài Gòn |\n|---|---|---|\n| Nước dùng | Trong, thanh | Ngọt đậm, béo |\n| Gia vị | Ít, tinh tế | Nhiều, phức tạp |\n| Rau sống | KHÔNG | Giá + húng + ngò |\n| Tương | Không tương đen | Tương đen + ớt |\n| Bánh phở | Mỏng, nhỏ | To bản, dai |\n| Triết lý | Ít mà tinh | Nhiều mà vui |\n\nFun fact: Phở gốc từ Nam Định, không phải Hà Nội hay Sài Gòn!",
        "grok-4": "Phở Hà Nội: tối giản chủ nghĩa. Nước trong veo, thịt bò + hành lá + quẩy. Done. Đừng dám bỏ tương đen vào — người Hà Nội sẽ nhìn bạn như nhìn ngoại tinh.\n\nPhở Sài Gòn: maximalist. Nước ngọt béo, rau sống đầy đĩa, tương đen tương ớt thoải mái. Thêm bò viên, gân, nạm — càng nhiều càng vui.\n\nTóm lại:\n- Hà Nội = iPhone (ít tính năng, nhưng tinh chỉnh từng chi tiết)\n- Sài Gòn = Android (tùy biến thoải mái, muốn gì có nấy)\n\nCả hai đều ngon. Chọn bên nào phụ thuộc vào tính cách bạn, không phải khẩu vị.",
        "deepseek": "Phở — hai trường phái:\n\n**Hà Nội (Bắc):**\n- Nước dùng: trong, thanh, ngọt xương tự nhiên\n- Rau: chỉ hành lá + mùi\n- Gia vị: chanh + ớt (KHÔNG tương đen)\n- Phong cách: ít mà chất\n\n**Sài Gòn (Nam):**\n- Nước dùng: ngọt đậm, béo, có hồi\n- Rau: giá, húng, ngò gai, rau om\n- Gia vị: tương đen, tương ớt, chanh\n- Phong cách: nhiều và hào phóng\n\nGốc phở: Nam Định (đầu thế kỷ 20). Cả hai phiên bản đều authentic theo cách riêng.",
        "llama-4": "Phở Hà Nội và phở Sài Gòn khác nhau ở triết lý ẩm thực:\n\n**Phở Hà Nội** — \"Less is more\"\n- Nước dùng trong, thanh, ninh xương 12-24 giờ\n- Gia vị tối giản: hành, mùi, quẩy\n- Không rau sống, không tương đen\n- Phở phải đúng vị, không cần thêm gì\n\n**Phở Sài Gòn** — \"More is more\"\n- Nước ngọt đậm, thêm đường phèn và gia vị\n- Đĩa rau sống: giá, húng quế, ngò gai\n- Tương đen, tương ớt sriracha\n- Tự do customize theo ý thích\n\nCả hai đều phản ánh văn hóa vùng miền: Bắc cầu kỳ tinh tế, Nam phóng khoáng thoải mái.",
        "qwen-35": "Phở Hà Nội vs Phở Sài Gòn — so sánh chi tiết:\n\n**Nước dùng:**\n- HN: trong veo, vị thanh, ninh thuần xương bò/gà\n- SG: ngọt đậm hơn, thêm đường phèn, có vị hồi và quế\n\n**Bánh phở:**\n- HN: sợi nhỏ, mỏng, mềm\n- SG: sợi to bản hơn, dai hơn\n\n**Ăn kèm:**\n- HN: hành lá, rau mùi, quẩy. Tuyệt đối không rau sống\n- SG: đĩa rau sống lớn (giá, húng quế, ngò gai, rau om), tương đen, tương ớt\n\n**Tính cách:**\n- HN: tinh tế, cầu kỳ — phở là nghệ thuật\n- SG: phóng khoáng, hào phóng — phở là niềm vui\n\nThú vị: phở gốc Nam Định, du nhập Hà Nội đầu 1900s, vào Sài Gòn sau 1954.",
        "glm-5": "So sánh phở hai miền:\n\n**Phở Hà Nội:**\n- Đặc trưng: thanh đạm, tinh tế, tối giản\n- Nước: trong, ngọt từ xương, ít gia vị\n- Ăn kèm: hành, mùi, quẩy — không gì hơn\n- Triết lý: \"đã ngon thì không cần thêm\"\n\n**Phở Sài Gòn:**\n- Đặc trưng: phong phú, đậm đà, tùy biến\n- Nước: ngọt béo, thêm gia vị phức tạp\n- Ăn kèm: rau sống, tương đen, tương ớt, chanh\n- Triết lý: \"ăn phải vui, phải đủ đầy\"\n\nKhông ai đúng ai sai — mỗi bát phở là một câu chuyện văn hóa.",
        "kimi-k25": "Phở Hà Nội = thanh + tối giản.\nPhở Sài Gòn = đậm + phong phú.\n\nChi tiết:\n- **Nước dùng:** HN trong thanh, SG ngọt béo\n- **Rau:** HN chỉ hành + mùi, SG cả \"vườn rau\" trên bàn\n- **Tương:** HN không dùng tương đen (sacrilege!), SG tương đen là must-have\n- **Bánh phở:** HN mỏng nhỏ, SG to bản dai\n- **Topping:** HN đơn giản (bò tái/chín), SG nhiều lựa chọn (bò viên, gân, nạm, gầu)\n\nPhở gốc Nam Định, nhưng Hà Nội và Sài Gòn đã biến nó thành hai kiệt tác riêng.",
        "mistral-l2": "Phở — biểu tượng ẩm thực Việt Nam — có hai phong cách chính:\n\n**Style Hà Nội (Bắc):**\n- Nước dùng: transparent, subtle, xương bò ninh lâu\n- Accompaniments: hành lá, rau mùi, quẩy. C'est tout.\n- Không rau sống, không tương đen\n- Philosophy: purity, minimalism\n\n**Style Sài Gòn (Nam):**\n- Nước dùng: richer, sweeter, more complex spicing\n- Accompaniments: giá, húng quế, ngò gai, chanh, ớt\n- Tương đen + sriracha on the side\n- Philosophy: abundance, customization\n\nLes deux sont authentiques — just different expressions of the same culinary tradition.",
    },
    6: {  # Viết email xin nghỉ phép
        "claude-sonnet": "Kính gửi Anh/Chị [Tên sếp],\n\nEm xin phép nghỉ [X] ngày, từ [ngày bắt đầu] đến [ngày kết thúc], lý do: [cá nhân/sức khỏe/gia đình].\n\n**Phương án bàn giao:**\n- Task A: [Đồng nghiệp 1] phụ trách\n- Task B: Đã hoàn thành trước deadline\n- Task C: Cập nhật tiến độ trên [Jira/Notion]\n\nEm có thể liên lạc qua điện thoại/email trong trường hợp khẩn cấp.\n\nKính mong Anh/Chị phê duyệt. Em xin cảm ơn!\n\nTrân trọng,\n[Họ tên]\n[Phòng ban] · [SĐT]",
        "gemini-flash": "**Subject:** Xin nghỉ phép [ngày] - [Họ tên]\n\nKính gửi Anh/Chị,\n\nEm xin phép nghỉ từ [ngày bắt đầu] đến [ngày kết thúc] ([X] ngày làm việc).\n\nLý do: [Việc cá nhân cần giải quyết]\n\nEm đã:\n✅ Bàn giao công việc cho [tên đồng nghiệp]\n✅ Hoàn thành deadline trước ngày nghỉ\n✅ Cập nhật tiến độ trên hệ thống\n\nNếu có việc gấp, em có thể liên lạc qua: [SĐT]\n\nMong Anh/Chị xem xét.\n\nTrân trọng,\n[Họ tên]",
        "grok-4": "Subject: Xin nghỉ phép [số ngày] ngày — [Họ tên]\n\nAnh/Chị [tên sếp] ơi,\n\nEm xin phép nghỉ từ [ngày] đến [ngày] vì [lý do ngắn gọn].\n\nĐã bàn giao:\n- [Task 1] → [Người thay]\n- [Task 2] → Đã xong\n\nSĐT em: [số], gọi bất cứ lúc nào nếu cần.\n\nCảm ơn Anh/Chị!\n\n[Họ tên]",
        "deepseek": "Kính gửi Anh/Chị [Tên],\n\nEm kính xin nghỉ phép [X] ngày: [ngày] → [ngày].\nLý do: [cá nhân/gia đình/sức khỏe].\n\nBàn giao:\n• Dự án A: [đồng nghiệp] tiếp quản\n• Dự án B: đã hoàn thành\n• Liên hệ khẩn: [email/SĐT]\n\nRất mong được phê duyệt.\n\nTrân trọng,\n[Họ tên] — [Phòng ban]",
        "llama-4": "**Subject:** [Họ tên] — Xin nghỉ phép ngày [X]\n\nKính gửi Anh/Chị,\n\nEm viết mail này để xin phép nghỉ phép [X] ngày làm việc, từ ngày [bắt đầu] đến ngày [kết thúc].\n\nLý do: [Giải quyết việc cá nhân/gia đình]\n\nĐể đảm bảo công việc không bị ảnh hưởng:\n1. Em đã bàn giao task quan trọng cho [tên đồng nghiệp]\n2. Tất cả deadline trong tuần đã hoàn thành\n3. Em sẵn sàng hỗ trợ qua điện thoại nếu cần\n\nMong Anh/Chị xem xét và phê duyệt.\n\nTrân trọng,\n[Họ tên]\n[Chức vụ] · [Phòng ban]",
        "qwen-35": "Chủ đề: Đơn xin nghỉ phép — [Họ tên] — [Ngày]\n\nKính gửi Anh/Chị [Tên sếp],\n\nEm kính xin phép nghỉ [X] ngày, từ [dd/mm] đến [dd/mm].\n\n📌 Lý do: [Việc cá nhân/Sức khỏe/Gia đình]\n\n📋 Bàn giao công việc:\n| Task | Người nhận | Trạng thái |\n|------|-----------|------------|\n| Task A | [Tên] | Đã bàn giao |\n| Task B | — | Đã hoàn thành |\n\n📱 Liên hệ khẩn cấp: [SĐT] / [Email]\n\nKính mong Anh/Chị phê duyệt.\n\nTrân trọng,\n[Họ tên]",
        "glm-5": "Kính gửi Anh/Chị,\n\nEm xin phép nghỉ từ [ngày bắt đầu] đến [ngày kết thúc], tổng [X] ngày làm việc.\n\nLý do: [lý do cụ thể]\n\nTrong thời gian nghỉ, [đồng nghiệp] sẽ xử lý công việc của em. Em đã hoàn tất bàn giao và cập nhật tiến độ.\n\nEm sẵn sàng hỗ trợ qua điện thoại nếu có việc khẩn.\n\nMong Anh/Chị xem xét.\n\nTrân trọng,\n[Họ tên]\n[Phòng ban]",
        "kimi-k25": "Subject: Xin nghỉ phép [X] ngày — [Họ tên]\n\nAnh/Chị thân mến,\n\nEm xin phép nghỉ [X] ngày từ [ngày] đến [ngày] để [lý do ngắn gọn].\n\n✅ Đã bàn giao: [tên task] cho [đồng nghiệp]\n✅ Deadline tuần này: đã hoàn thành\n✅ Liên hệ: [SĐT] — sẵn sàng hỗ trợ remote\n\nCảm ơn Anh/Chị đã xem xét!\n\nTrân trọng,\n[Họ tên]",
        "mistral-l2": "Objet: Demande de congé — À, tiếng Việt nhé!\n\nKính gửi Anh/Chị [Tên sếp],\n\nEm xin phép nghỉ phép [X] ngày, từ ngày [bắt đầu] đến ngày [kết thúc].\n\nLý do: [Việc cá nhân cần giải quyết]\n\nĐể đảm bảo continuité du travail — à, sự liên tục công việc:\n- Em đã bàn giao đầy đủ cho [đồng nghiệp]\n- Các deadline quan trọng đã hoàn thành\n- Em có thể liên lạc qua [SĐT/email]\n\nKính mong Anh/Chị phê duyệt.\n\nCordialement — Trân trọng,\n[Họ tên]",
    },
    7: {  # Tóm tắt hiệp định Geneva 1954
        "claude-sonnet": "**5 câu tóm tắt Hiệp định Geneva 1954:**\n\n1. Hiệp định ký ngày 21/7/1954 tại Geneva (Thụy Sĩ), chấm dứt chiến tranh Đông Dương sau chiến thắng Điện Biên Phủ của Việt Minh.\n\n2. Việt Nam tạm chia hai tại vĩ tuyến 17: miền Bắc do VNDCCH (Hồ Chí Minh) quản lý, miền Nam do Quốc gia Việt Nam kiểm soát.\n\n3. Hai bên ngừng bắn, trao đổi tù binh, dân chúng được tự do di cư giữa hai miền trong 300 ngày.\n\n4. Dự kiến tổng tuyển cử thống nhất vào 7/1956, nhưng Ngô Đình Diệm (được Mỹ hậu thuẫn) từ chối — cuộc bầu cử không bao giờ diễn ra.\n\n5. Hiệp định cũng công nhận độc lập Lào và Campuchia, đánh dấu sự kết thúc của chủ nghĩa thực dân Pháp tại Đông Dương.",
        "gemini-flash": "Hiệp định Geneva 1954 — 5 câu:\n\n1. Ký 21/7/1954 sau khi Pháp thua trận Điện Biên Phủ (7/5/1954).\n\n2. Việt Nam chia đôi tại vĩ tuyến 17: Bắc = VNDCCH, Nam = Quốc gia VN.\n\n3. Ngừng bắn toàn Đông Dương, trao đổi tù binh, cho phép di cư tự do.\n\n4. Tổng tuyển cử thống nhất dự kiến 7/1956 — không bao giờ xảy ra vì miền Nam từ chối.\n\n5. Kết thúc 100 năm thuộc Pháp, nhưng mở đầu 20 năm chia cắt và chiến tranh Việt Nam.",
        "grok-4": "Geneva 1954 trong 5 câu:\n\n1. Pháp thua Điện Biên Phủ → ngồi vào bàn đàm phán ở Geneva.\n2. Kết quả: VN chia đôi tại vĩ tuyến 17. Bắc = Hồ Chí Minh, Nam = Bảo Đại (rồi Ngô Đình Diệm).\n3. Deal: ngừng bắn, đổi tù, tổng tuyển cử 1956.\n4. Plot twist: Diệm + Mỹ nói \"không\" với bầu cử → chia cắt vĩnh viễn.\n5. Legacy: kết thúc thuộc Pháp, nhưng mở ra Chiến tranh Việt Nam — cuộc chiến đau thương nhất thế kỷ 20.",
        "deepseek": "Tóm tắt Geneva 1954:\n\n1. **Bối cảnh:** Pháp thất bại tại Điện Biên Phủ (7/5/1954), buộc phải đàm phán tại Geneva.\n\n2. **Nội dung:** VN tạm chia tại vĩ tuyến 17. Ngừng bắn, rút quân, đổi tù binh.\n\n3. **Cam kết:** Tổng tuyển cử thống nhất vào tháng 7/1956 dưới giám sát quốc tế.\n\n4. **Thực tế:** Ngô Đình Diệm từ chối bầu cử (Mỹ ủng hộ) → đất nước chia cắt kéo dài.\n\n5. **Ý nghĩa:** Kết thúc thuộc địa Pháp nhưng gieo mầm cho 20 năm chiến tranh tiếp theo.",
        "llama-4": "**Hiệp định Geneva 1954 — Tóm tắt 5 câu:**\n\n1. Sau chiến thắng lịch sử tại Điện Biên Phủ, Việt Minh và Pháp ký hiệp định hòa bình tại Geneva ngày 21/7/1954.\n\n2. Việt Nam bị chia tạm thời tại vĩ tuyến 17 — phía Bắc thuộc VNDCCH, phía Nam thuộc Quốc gia VN.\n\n3. Các bên đồng ý ngừng bắn, trao đổi tù binh, và cho phép di cư tự do trong 300 ngày.\n\n4. Tổng tuyển cử thống nhất dự kiến tổ chức vào 7/1956 nhưng không bao giờ diễn ra do miền Nam từ chối tham gia.\n\n5. Hiệp định đánh dấu sự chấm dứt của chế độ thực dân Pháp tại Đông Dương, nhưng cũng mở đầu cho cuộc Chiến tranh Việt Nam.",
        "qwen-35": "Geneva 1954 — 5 điểm chính:\n\n1. 🗓️ Ký 21/7/1954 tại Geneva, Thụy Sĩ — sau khi Pháp đại bại ở Điện Biên Phủ.\n\n2. 🗺️ VN tạm chia đôi tại vĩ tuyến 17: Bắc (VNDCCH) và Nam (Quốc gia VN).\n\n3. ⚖️ Ngừng bắn, trao đổi tù binh, 300 ngày di cư tự do (khoảng 1 triệu người Bắc di cư vào Nam).\n\n4. ❌ Tổng tuyển cử 1956 bị Ngô Đình Diệm + Mỹ bác bỏ → chia cắt kéo dài → dẫn đến Chiến tranh VN.\n\n5. 🏛️ Đánh dấu sự sụp đổ của đế chế thuộc địa Pháp tại Đông Dương (VN, Lào, Campuchia đều được công nhận độc lập).",
        "glm-5": "5 câu về Hiệp định Geneva 1954:\n\n1. Hiệp định ký 21/7/1954, kết thúc 9 năm kháng chiến chống Pháp sau chiến thắng Điện Biên Phủ.\n\n2. Việt Nam tạm thời chia hai tại vĩ tuyến 17 — Bắc theo VNDCCH, Nam theo Quốc gia VN.\n\n3. Quy định ngừng bắn, đổi tù binh, di cư tự do, và cấm các bên gia nhập liên minh quân sự.\n\n4. Tổng tuyển cử thống nhất dự kiến 7/1956 nhưng bị miền Nam từ chối — dẫn đến 20 năm chia cắt.\n\n5. Hiệp định công nhận độc lập của VN, Lào, Campuchia — chấm dứt gần 100 năm đô hộ của Pháp.",
        "kimi-k25": "Hiệp định Geneva 1954 — bản tóm tắt:\n\n1. Pháp thua Điện Biên Phủ → hội nghị quốc tế tại Geneva bàn về hòa bình Đông Dương.\n2. VN tạm chia tại vĩ tuyến 17. Bắc = Hồ Chí Minh. Nam = Quốc gia VN.\n3. Ngừng bắn + đổi tù + di cư tự do 300 ngày.\n4. Hẹn bầu cử thống nhất 1956 — Diệm từ chối, Mỹ đồng ý → bầu cử hủy → chia cắt.\n5. Kết thúc thuộc Pháp, nhưng mở ra chương mới đau thương: Chiến tranh Việt Nam (1955-1975).",
        "mistral-l2": "Les Accords de Genève — bằng tiếng Việt:\n\n1. Ký 21/7/1954 sau thất bại của Pháp tại Điện Biên Phủ — trận đánh thay đổi lịch sử.\n\n2. VN tạm chia đôi tại vĩ tuyến 17: VNDCCH (Bắc) và Quốc gia VN (Nam).\n\n3. Ngừng bắn toàn Đông Dương. Trao đổi tù binh. Di cư tự do 300 ngày.\n\n4. Tổng tuyển cử thống nhất 7/1956 — không bao giờ diễn ra. Ngô Đình Diệm và Washington từ chối.\n\n5. Résultat: kết thúc colonialisme français nhưng mở đầu cho cuộc chiến mới kéo dài 20 năm.",
    },
    8: {  # Viết truyện ngắn kinh dị Đà Lạt
        "claude-sonnet": "**Căn Phòng Số 4**\n\nLinh đặt homestay ở đường Phan Đình Phùng. Giá rẻ bất ngờ — 150k/đêm cho biệt thự Pháp cổ.\n\nChủ nhà nhắn: \"Phòng số 3 nhé. Đừng vào phòng số 4.\"\n\nĐêm đầu, Linh nghe tiếng khóc qua vách. Nhẹ, đều, như trẻ con. Cô tự nhủ: gió Đà Lạt.\n\nĐêm thứ hai, tiếng khóc gần hơn. Ngay bên ngoài cửa phòng 4. Linh áp tai vào vách — tiếng khóc dừng. Rồi có tiếng thì thầm: \"Mở cửa đi...\"\n\nĐêm thứ ba, Linh tỉnh dậy lúc 2:47. Cửa phòng 4 đang hé mở. Bên trong tối đen. Nhưng trên sàn, có một đôi dép nhỏ — đôi dép trẻ con — đang quay mũi ra ngoài.\n\nLinh chạy xuống lầu. Khi quay lại nhìn — cả 4 phòng đều tối. Nhưng chỉ phòng số 4 có ánh sáng hắt qua khe cửa.\n\nCô check-out lúc 3 giờ sáng. Google Maps hiện: \"Biệt thự này đã ngưng hoạt động từ 2019 sau vụ cháy.\"",
        "gemini-flash": "**Bức Ảnh Cuối**\n\nNhóm 3 bạn lên Đà Lạt chụp ảnh. Huy — photographer — mê những nơi hoang vắng.\n\nHọ tìm thấy một nhà thờ bỏ hoang trên đồi, sương mù bao phủ. Huy chụp liên tục.\n\n\"Nhìn này\" — Huy zoom vào ảnh vừa chụp. Trong khung cửa sổ nhà thờ, có bóng một người phụ nữ mặc áo dài trắng đang nhìn xuống.\n\n\"Photoshop chắc\" — Lan cười.\n\nHuy chụp thêm 10 tấm. Tấm nào cũng có bóng trắng — nhưng mỗi tấm, bóng lại gần hơn một chút.\n\nTấm cuối cùng: bóng trắng đứng ngay sau lưng Huy.\n\nKhi cả nhóm quay lại xem ảnh ở khách sạn, máy ảnh chỉ còn 1 tấm duy nhất — chụp 3 người từ phía sau, đang đi vào sương mù. Nhưng trong ảnh có 4 bóng người.",
        "grok-4": "**WiFi Miễn Phí**\n\nĐà Lạt, 11 giờ đêm. Tuấn ngồi trong quán café sương mù, scroll phone.\n\nWiFi quán yếu. Điện thoại tự kết nối một mạng lạ: \"BIET_THU_CU_FREE.\"\n\nTuấn vào. Nhanh phết. Anh lướt Facebook bình thường.\n\nRồi anh thấy — Facebook hiện một bài post từ chính tài khoản mình. Đăng 5 phút trước. Ảnh chụp Tuấn... từ phía sau... ngồi đúng chỗ này.\n\nTuấn quay đầu lại. Quán trống. Không có ai.\n\nAnh nhìn lại màn hình. Bài post đã xóa. Nhưng có 1 comment trước khi xóa, từ một tài khoản không có ảnh đại diện:\n\n\"Đừng quay lại lần nữa.\"",
        "deepseek": "**Sương Mù Đồi Cù**\n\nMinh chạy bộ sáng trên Đồi Cù. 5 giờ sáng. Sương dày đặc.\n\nAnh chạy theo đường quen — vòng quanh đồi, 3km. Nhưng hôm nay, chạy mãi không hết vòng.\n\n10 phút. 20 phút. 30 phút. Vẫn cùng một đoạn đường.\n\nMinh dừng lại, bật GPS. Chấm xanh hiện đúng vị trí — nhưng bản đồ hiện: \"Bạn đang ở ngoài khu vực bản đồ.\"\n\nSương bắt đầu tan. Minh nhìn quanh — không phải Đồi Cù. Đây là một nghĩa trang cũ. Những ngôi mộ rêu phong xếp thành hàng. Trên mộ gần nhất, tấm bia ghi: tên anh. Ngày mất: hôm nay.",
        "llama-4": "**Tiếng Chuông**\n\nNga thuê phòng trong một villa cũ đường Trần Lê. Chủ nhà — bà cụ 80 tuổi — đưa chìa khóa và nói: \"Nếu nghe tiếng chuông ban đêm, đừng ra ngoài.\"\n\nĐêm đầu: yên tĩnh.\n\nĐêm hai: 1 giờ sáng, tiếng chuông. Nhẹ, xa, như chuông nhà thờ. Nga nhìn qua cửa sổ — sương mù trắng xóa, không thấy gì.\n\nĐêm ba: tiếng chuông lại vang. Gần hơn. Rõ hơn. Rồi có tiếng gõ cửa. 3 tiếng. Đều đặn.\n\nNga mở cửa — bà cụ chủ nhà đứng đó, mỉm cười.\n\n\"Tôi bảo đừng ra ngoài mà.\"\n\nNga đóng sầm cửa. Sáng hôm sau, hàng xóm nói: \"Bà cụ đó mất 3 năm rồi em ơi. Villa này bỏ hoang lâu rồi.\"",
        "qwen-35": "**Người Lái Xe Ôm Đêm**\n\nĐà Lạt, 11 giờ đêm. Khánh gọi xe ôm từ chợ đêm về khách sạn.\n\nMột ông già đội mũ cối lái xe Wave cũ đến. Không dùng app. Không biển số.\n\n\"Lên đi cháu. Đường này tối lắm.\"\n\nKhánh lên xe. Ông già chạy nhanh — qua những con đường Khánh không nhận ra. Sương mù dày đặc.\n\n\"Ông ơi, đi đường nào vậy?\"\n\nÔng già không trả lời. Xe cứ chạy.\n\nRồi đột ngột dừng. Trước mặt là một ngôi nhà cũ nát. Ông già nói: \"Tới rồi.\"\n\n\"Đây không phải khách sạn tôi!\"\n\nKhánh quay sang — ghế sau trống. Không có ai lái xe. Xe Wave đứng giữa đường, máy tắt. Trước mặt là nghĩa trang Đà Lạt.\n\nĐêm đó, Khánh đi bộ 4km về khách sạn. Google Maps xác nhận: con đường ông già chạy không tồn tại trên bản đồ.",
        "glm-5": "**Chiếc Gương Cũ**\n\nMai mua một chiếc gương cổ ở chợ đồ xưa Đà Lạt. Khung gỗ chạm hoa, kiểu Pháp.\n\nĐêm đầu, Mai soi gương trước khi ngủ. Phản chiếu bình thường.\n\nĐêm thứ hai, Mai nhận ra: trong gương, đồng hồ trên tường chỉ 3:00. Nhưng giờ thực là 11:00.\n\nĐêm thứ ba, phản chiếu trong gương không phải phòng cô. Đó là một căn phòng cũ — giấy dán tường bong tróc, nến cháy dở. Và có một người phụ nữ ngồi quay lưng.\n\nMai bước lại gần. Người phụ nữ trong gương cũng bước lại gần.\n\nRồi quay mặt lại.\n\nKhuôn mặt đó... là Mai. Nhưng già hơn 50 tuổi. Và khóc.",
        "kimi-k25": "**Homestay 5 Sao**\n\nReview trên app: 5.0 sao, 200+ đánh giá. \"View đẹp nhất Đà Lạt!\" \"Chủ nhà siêu thân thiện!\"\n\nTuấn đặt phòng. Đến nơi — biệt thự đẹp thật, trên đồi thông, sương mù bao quanh.\n\nChủ nhà — một anh trẻ — cười tươi: \"Chào anh! WiFi mạnh, bếp tự nấu thoải mái.\"\n\nĐêm đầu: hoàn hảo.\nĐêm hai: Tuấn tỉnh dậy vì lạnh. Cửa sổ mở toang. Anh nhớ rõ đã khóa.\nĐêm ba: 3 giờ sáng. Tuấn nghe tiếng bước chân trên mái nhà. Rồi tiếng gõ — từ trần nhà.\n\nSáng hôm sau, Tuấn check-out. Mở app xem lại review — homestay này chỉ có 2 review. Cả hai từ 2020. Cả hai viết cùng nội dung:\n\n\"Đừng ở đêm thứ 4.\"",
        "mistral-l2": "**La Brume — Sương Mù**\n\nSophie — du khách Pháp — đến Đà Lạt tìm dấu vết thuộc địa cũ.\n\nCô tìm thấy một biệt thự Pháp bỏ hoang trên đường Trần Hưng Đạo. Cổng sắt rỉ, vườn cỏ dại. Nhưng bên trong — đồ đạc vẫn nguyên: bàn gỗ sồi, đàn piano, ảnh đen trắng trên tường.\n\nSophie chụp ảnh. Trong một bức ảnh cũ trên tường: gia đình Pháp, 4 người, đứng trước chính biệt thự này. Năm 1953.\n\nCô nhìn kỹ hơn. Người phụ nữ trong ảnh... giống cô. Chính xác như soi gương.\n\nSophie bỏ chạy. Khi ra đến cổng, cô quay lại nhìn — trên ban công tầng 2, có một bóng người đang vẫy tay.\n\nVề Pháp, Sophie tìm lịch sử gia đình. Bà cố của cô từng sống ở Đà Lạt. Biệt thự đó là nhà bà. Bà mất năm 1954 — không bao giờ rời khỏi Việt Nam.",
    },
    9: {  # Phân tích VinFast
        "claude-sonnet": "**VinFast quốc tế — Phân tích SWOT:**\n\n**Strengths:**\n- Vingroup backing: tài chính mạnh, hệ sinh thái hỗ trợ\n- All-in EV: không gánh nặng xe xăng kế thừa\n- Giá cạnh tranh: VF 5 từ ~$20K, nhắm phân khúc thiếu vắng\n- IPO NASDAQ tạo nhận diện quốc tế\n\n**Weaknesses:**\n- Brand awareness gần 0 tại Mỹ/EU\n- Lỗ lũy kế lớn (~$2B/năm)\n- Review chất lượng trung bình từ báo quốc tế\n- Mạng lưới dịch vụ/sạc quá mỏng\n\n**Opportunities:**\n- Thị trường EV tăng 25%/năm\n- Phân khúc EV giá rẻ ($20-35K) còn nhiều dư địa\n- Trợ cấp chính phủ Mỹ/EU cho EV\n\n**Threats:**\n- BYD, Tesla — đối thủ cực mạnh\n- Cuộc chiến giá EV Trung Quốc\n- Thuế quan và tiêu chuẩn an toàn khác nhau mỗi thị trường",
        "gemini-flash": "**VinFast — Phân tích thẳng thắn:**\n\n✅ **Điểm mạnh:**\n- Tốc độ: 0 → NASDAQ trong 5 năm\n- All-in EV, không legacy ICE\n- VF 5 dưới $20K — phân khúc ít cạnh tranh\n- Vingroup = \"túi tiền sâu\"\n\n❌ **Điểm yếu:**\n- Brand = 0 ở phương Tây\n- Lỗ nặng, chưa có lãi\n- Chất lượng chưa thuyết phục reviewer quốc tế\n- Trạm sạc + dịch vụ quá ít\n\n⚡ **Cơ hội:** EV market growing 25%/year, government subsidies, affordable EV gap\n\n⚠️ **Rủi ro:** BYD giá rẻ hơn, Tesla brand mạnh hơn, thiếu runway nếu doanh số không tăng\n\n**Verdict:** Tham vọng đúng, execution cần cải thiện. Nên focus 2-3 thị trường thay vì 60+.",
        "grok-4": "VinFast trên sân chơi quốc tế? Thẳng thắn nhé:\n\n**Giỏi:**\n- Dám chơi lớn: IPO NASDAQ, xây nhà máy Mỹ, tham vọng toàn cầu\n- All-EV: không phải \"chuyển đổi\" như Toyota hay BMW — bắt đầu từ EV luôn\n- Giá ngon: VF 5 phân khúc $20K, VF 8 phân khúc $40K\n\n**Chưa giỏi:**\n- Brand: người Mỹ hỏi \"VinFast là gì?\" — đó là vấn đề lớn nhất\n- Tiền: đốt $2B/năm, bán được 35K xe/năm. Toán không ổn.\n- Dàn trải: 60+ thị trường cùng lúc? Tesla mất 10 năm mới ra khỏi Mỹ.\n\n**Lời khuyên không ai hỏi:** Bỏ 57 thị trường, focus 3: Việt Nam (home), Indonesia (emerging), EU (subsidy). Done.",
        "deepseek": "VinFast — phân tích ngắn gọn:\n\n**Mạnh:** Vingroup backing, all-EV strategy, giá cạnh tranh, NASDAQ listed.\n\n**Yếu:** Brand chưa có ở phương Tây, lỗ lớn, dịch vụ/sạc mỏng, chất lượng cần cải thiện.\n\n**Cơ hội:** EV boom toàn cầu, trợ cấp chính phủ, phân khúc EV giá rẻ còn trống.\n\n**Thách thức:** Tesla + BYD thống trị, cuộc chiến giá TQ, rào cản pháp lý khác nhau mỗi nước.\n\n**Key question:** Liệu Vingroup có đủ kiên nhẫn (và tiền) để chịu lỗ 5-7 năm nữa? Nếu có → VinFast có cơ hội. Nếu không → sẽ phải thu hẹp đáng kể.",
        "llama-4": "**Phân tích VinFast trên thị trường quốc tế:**\n\n**Điểm mạnh:**\n1. Vingroup support — tập đoàn lớn nhất VN, đủ lực tài chính\n2. Pure EV play — không có sản phẩm ICE kéo lại\n3. Giá cạnh tranh — VF 5 phân khúc entry-level EV\n4. Nhà máy tại Mỹ (North Carolina) — giảm thuế nhập khẩu\n\n**Điểm yếu:**\n1. Thương hiệu mới — zero brand equity tại Mỹ/EU\n2. Tài chính — lỗ $2B+/năm, chưa rõ breakeven\n3. Chất lượng — review từ media quốc tế chưa ấn tượng\n4. Hệ thống dịch vụ — quá ít showroom và trạm sạc\n\n**Chiến lược đề xuất:**\n- Thu hẹp từ 60+ xuống 5 thị trường trọng điểm\n- Focus VF 5 (giá rẻ) thay vì VF 8/9 (cạnh tranh quá khốc liệt)\n- Partnership với charging networks (ChargePoint, Ionity)",
        "qwen-35": "**VinFast 国际市场分析 — Phân tích thị trường quốc tế:**\n\n**Strengths (Mạnh):**\n- Vingroup ecosystem: bất động sản, bán lẻ, giáo dục → cross-selling potential\n- All-EV from day 1: không có ICE transition cost\n- Aggressive pricing: VF 5 ($20K), VF 6 ($25K) — undercut competitors\n- NASDAQ listed → access to capital markets\n\n**Weaknesses (Yếu):**\n- Brand recognition ≈ 0 outside Vietnam\n- Cumulative losses > $5B\n- JD Power, Consumer Reports ratings: below average\n- Charging + service network: minimal in target markets\n\n**Strategic assessment:** VinFast has the ambition and capital but lacks execution focus. Spreading across 60+ markets dilutes resources. Best path: dominate Vietnam + 2-3 emerging markets first, then expand.",
        "glm-5": "**Phân tích VinFast quốc tế:**\n\n**Điểm mạnh:**\n- Hậu thuẫn tài chính từ Vingroup\n- Chiến lược 100% xe điện\n- Giá bán cạnh tranh trong phân khúc\n- Có nhà máy tại Mỹ\n\n**Điểm yếu:**\n- Thương hiệu chưa được biết đến ở thị trường mục tiêu\n- Thua lỗ kéo dài, dòng tiền âm\n- Chất lượng sản phẩm cần cải thiện (theo đánh giá quốc tế)\n- Hạ tầng sạc và dịch vụ sau bán hàng quá mỏng\n\n**Nhận xét:** VinFast có tham vọng đáng ngưỡng mộ nhưng cần tập trung hơn. Thay vì mở rộng toàn cầu ngay, nên củng cố thị trường nội địa và chọn 2-3 thị trường quốc tế trọng điểm.",
        "kimi-k25": "VinFast quốc tế — nhìn từ góc độ khách quan:\n\n**Pro:**\n- Vingroup tài trợ: đủ tiền \"đốt\" vài năm nữa\n- All-in EV: lợi thế so với hãng truyền thống đang chuyển đổi\n- Giá VF 5 dưới $20K: phân khúc entry-level EV rất hấp dẫn\n\n**Con:**\n- \"VinFast là gì?\" — 99% người Mỹ/EU chưa nghe tên\n- Lỗ $2B/năm. Bán 35K xe/năm. Unit economics chưa work.\n- Dàn trải 60+ thị trường = phân tán nguồn lực\n- After-sales: không đủ trạm sạc, service center\n\n**Bottom line:** VinFast cần 3 thứ: focus (2-3 markets), patience (5+ years), và quality (phải vượt kỳ vọng, không chỉ đạt mức trung bình).",
        "mistral-l2": "**Analyse de VinFast — Phân tích VinFast:**\n\n**Forces (Mạnh):**\n- Vingroup financial backing — le plus grand conglomérat du Vietnam\n- Pure EV strategy — pas de legacy ICE\n- Prix compétitifs — VF 5 à partir de $20K\n- NASDAQ IPO → global visibility\n\n**Faiblesses (Yếu):**\n- Zéro brand awareness en Occident\n- Pertes massives — ~$2B par an\n- Qualité — reviews mitigées (MotorTrend, Car & Driver)\n- Réseau de service insuffisant\n\n**Opportunités:** Marché EV en croissance 25%/an, subventions gouvernementales, segment affordable EV peu exploité\n\n**Menaces:** Tesla, BYD dominent. Guerre des prix en cours. Barrières réglementaires variables.\n\n**Mon avis:** VinFast a le mérite de l'ambition — mais l'exécution doit s'améliorer significativement. Focus sur 3 marchés maximum.",
    },
}


async def migrate():
    async with aiosqlite.connect(DATABASE_PATH) as db:
        inserted = 0
        for prompt_id, model_responses in NEW_RESPONSES.items():
            for model_id, content in model_responses.items():
                # Check if response already exists
                cursor = await db.execute(
                    "SELECT id FROM responses WHERE prompt_id = ? AND model_id = ? AND turn_number = 1",
                    (prompt_id, model_id),
                )
                if await cursor.fetchone():
                    continue
                await db.execute(
                    "INSERT INTO responses (prompt_id, model_id, content, turn_number) VALUES (?, ?, ?, 1)",
                    (prompt_id, model_id, content),
                )
                inserted += 1
        await db.commit()
        print(f"Inserted {inserted} new responses")


if __name__ == "__main__":
    asyncio.run(migrate())
